package:
  name: vina
  version: "1.1.2"

source:
  path: .

build:
  number: 3

requirements:
  build:
    - python >=3.4
  run:
    - python >=3.4
    - htmdbabel >=2.1

   
about:
  license: "Apache"
