package:
  name: boto3
  version: "0.0.1"

source:
   git_url: https://github.com/boto/boto3.git

build:
  number: 1

requirements:

  build:
    - python >=3.4

  run:
    - python  >=3.4
    
about:
  license: "LGPL 2.1"
