package:
  name: openmm
  version: "7.0.0"

source:
   git_url: https://github.com/pandegroup/openmm

build:
  number: 3

requirements:

  build:
    - python >=3.5

  run:
    - python >=3.5
    
about:
  license: "LGPL 2.1"
