package:
  name: openmm
  version: "7.0.0"

source:
   git_url: https://github.com/pandegroup/openmm

build:
  number: 2

requirements:

  build:
    - python 

  run:
    - python 
    
about:
  license: "LGPL 2.1"
