package:
  name: botocore
  version: "0.0.3"

source:
   git_url: https://github.com/boto/botocore.git

build:
  number: 1

requirements:

  build:
    - python >=3.4

  run:
    - python  >=3.4
    - jmespath >=0.0.2
    
about:
  license: "LGPL 2.1"
