package:
  name:  htmdbabel
  version: "2.3.90"

source:
  git_url: https://github.com/mj-harvey/openbabel.git

build:
  number: 1
 
requirements:
  build:
    - python
  run:
    - python
   
about:
  license: "GPL 2"
