package:
  name:  boxsdk
  version: "1.1.2"

source:
  git_url: https://github.com/box/box-python-sdk

build:
  number: 1
 
requirements:
  build:
    - python
    - six
    - requests
    - cryptography
    - pyjwt
  run:
    - python
    - six
    - requests
    - cryptography
    - pyjwt
about:
  license: "Apache 2"
