package:
  name: jmespath
  version: "0.0.2"

source:
   git_url: https://github.com/jmespath/jmespath.py

build:
  number: 1

requirements:

  build:
    - python >=3.4

  run:
    - python  >=3.4
    
about:
  license: "LGPL 2.1"
