package:
  name: nglview
  version: "0.0.1"

source:
   git_url: https://github.com/arose/nglview

build:
  number: 1

requirements:

  build:
    - python 

  run:
    - python 
    
about:
  license: "LGPL 2.1"
