package:
  name: propka
  version: "3.1"

source:
   git_url: https://github.com/jensengroup/propka-3.1

build:
  number: 2

requirements:

  build:
    - python 

  run:
    - python 
    
about:
  license: "LGPL 2.1"
