package:
  name: nlopt
  version: "2.4.2"

source:
  path: .

build:
  number: 1

requirements:

  build:
    - python 
    - numpy

  run:
    - python 
    - numpy
    
about:
  license: "LGPL 2.1"
